steps:
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/sample-gcp-app:${TAG_NAME}', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/$PROJECT_ID/sample-gcp-app"]
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'sample-gcp-app', '--image', 'gcr.io/$PROJECT_ID/sample-gcp-app:${TAG_NAME}', '--region', 'us-central1']