steps:
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/sample-gcp-app', '.']
- name: gcr.io/cloud-builders/docker
  args: ['run', '--rm', 'gcr.io/$PROJECT_ID/sample-gcp-app', 'python', '-m', 'unittest', 'discover', '-v', '-s', 'tests']
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/$PROJECT_ID/sample-gcp-app"]
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - beta
  - run
  - deploy
  - sample-gcp-app
  - --allow-unauthenticated
  - --image
  - gcr.io/$PROJECT_ID/sample-gcp-app
  - --region
  - us-central1
images:
- gcr.io/$PROJECT_ID/sample-gcp-app