steps:
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/sample-gcp-app', '.']
- name: gcr.io/cloud-builders/docker
  args: ['run', '--rm', 'gcr.io/$PROJECT_ID/sample-gcp-app', 'python', '-m', 'unittest', 'discover', '-v', '-s', 'tests']
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/$PROJECT_ID/sample-gcp-app"]
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - beta
  - run
  - deploy
  - sample-gcp-app
  - --allow-unauthenticated
  - --image
  - gcr.io/$PROJECT_ID/sample-gcp-app
  - --region
  - us-central1
  - --set-env-vars
  - >-
    MONGODB_CONNECTION_STRING=$$MONGODB_CONNECTION_STRING,
    MONGODB_DATABASE=sampleGcpAppProd
  secretEnv:
  - MONGODB_CONNECTION_STRING
images:
- gcr.io/$PROJECT_ID/sample-gcp-app
secrets:
- kmsKeyName: projects/sample-gcp-app/locations/global/keyRings/default/cryptoKeys/sample-gcp-app
  secretEnv:
    MONGODB_CONNECTION_STRING: CiQA82pG8IYK/93VVik9ZZEsnufMmNK5AKtZ1YiX/GcyZsGwXroS2wIA7OBpB8VBAxzo1H2DoBcpoTEwWa/8q4HIeSrKh9NbQXSncPhMUXeOm/6Cn9ODbg1NRiaJi24aBRXJAlTw3Zov32NRfJQRNbtWszeubZMO/J8BvN478SV4pyOqmA/0AivPmRlczIOz4np57ozSK5V/sKNM9dkLew8yf3QW8RCoVuFXjjP+PlLOQTI7AYcAf6Vuw8XaGg1/kmRbQ5aGE+pQQsQQhQrQ6ioHvOr9Dj97y07wzr9nFPF93urxWClogXMW111WWM6/M429aigsHcC5/LKsntZMq/TZgTN4oKUyfBpHA3YPL2hi2+IiqMghoTaC/bdxAiL1tyYwIF28xY3mcz3gKXPf6ZXdFMpgN07e7Hr9Z8ngYof2UO6gV0RGITmRYJSEnjlXwVC2nMnFJzYKD3GF0o9KPcIqSfwLntyZ+HijTG/t8hVpuVlzaTa4ht829SVKxo/iS/pK7g==
