steps:
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/sample-gcp-app-dev', '.']
- name: gcr.io/cloud-builders/docker
  args: ['run', '--rm', 'gcr.io/$PROJECT_ID/sample-gcp-app-dev', 'python', '-m', 'unittest', 'discover', '-v', '-s', 'tests']
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/$PROJECT_ID/sample-gcp-app-dev"]
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - beta
  - run
  - deploy
  - sample-gcp-app-dev
  - --allow-unauthenticated
  - --image
  - gcr.io/$PROJECT_ID/sample-gcp-app-dev
  - --region
  - us-central1
  - --set-env-vars
  - >-
    MONGODB_CONNECTION_STRING=$$MONGODB_CONNECTION_STRING,
    MONGODB_DATABASE=sampleGcpAppStaging
  secretEnv:
  - MONGODB_CONNECTION_STRING
images:
- gcr.io/$PROJECT_ID/sample-gcp-app-dev
secrets:
- kmsKeyName: projects/sample-gcp-app/locations/global/keyRings/default/cryptoKeys/sample-gcp-app
  secretEnv:
    MONGODB_CONNECTION_STRING: CiQA82pG8BCN0ucD1oRc9lehKBD0JtSZHHkAbq5Hj3QSRS/B/PcS3gIA7OBpB1Sv4FvRd8rJNfGYGUGhdg3JWoRSXTZ3C7RDZlszp9F4Uu357/8ZFBI5o1zfFx0aR61h6Mpb0PPeERlSz0ot4BgzJyrs7bJ5t6NJhe3taHkVmh0x5k+7h3CammmN2O6Tz1M2JWZt/5O0D+S9YUnWssQgk2KncjLhVj0hdrqPa9Z+TlgPun8splrNpdLnupnj0ObJzVszKFzEWkssB66MxOSewjVIr6PqhPfHZtYuiLHBpZiB0Dg2rbI9okaYG25YhFeG7rhAxBF+lD8iaDxujZijppeRpRbC5AeHANKbsrD7KNcVSapydvf9P6+3wSwIKZAztXXEPTRbRjUa/cYL7k+dTYhpSF25wmFQm2btTt4wRv5t+6Kbn+CH+6yOqdZYqtR5XBheX/4WXvhl7rw73R4hWfRG8Siz32zd+mDGpMxdTJESV7gYwCgh5GVEvj+MZVvSsL1M3cNe1A==
