steps:
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/sample-gcp-app-dev', '.']
- name: gcr.io/cloud-builders/docker
  args: ['run', '--rm', 'gcr.io/$PROJECT_ID/sample-gcp-app-dev', 'python', '-m', 'unittest', 'discover', '-v', '-s', 'tests']
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/$PROJECT_ID/sample-gcp-app-dev"]
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - beta
  - run
  - deploy
  - sample-gcp-app-dev
  - --allow-unauthenticated
  - --image
  - gcr.io/$PROJECT_ID/sample-gcp-app-dev
  - --region
  - us-central1
  - --set-env-vars
  - >-
    MONGODB_DATABASE=sample_gcp_app_staging,
    MONGODB_USERNAME=app_user,
    MONGODB_PASSWORD=$$MONGODB_PASSWORD,
    MONGODB_HOST=$$MONGODB_HOST,
    MONGODB_PORT=27017,
    MONGODB_USE_SRV=true
  secretEnv:
  - MONGODB_PASSWORD
  - MONGODB_HOST
images:
- gcr.io/$PROJECT_ID/sample-gcp-app-dev
secrets:
- kmsKeyName: projects/sample-gcp-app/locations/global/keyRings/default/cryptoKeys/sample-gcp-app
  secretEnv:
    MONGODB_HOST: CiQA82pG8DzHURlfR71LNVqqeRfO8bBrDRMxiYeIkB1agV8KI+QSTQDs4GkHS6rAwon68kOeSzf1Ij0HI8eNy17K3/ZSKlmPXQuOOY+kcawaE79hF6rE6182CR9I9vEYYRIeK6JCT/CT/bA1IwZ853bkWznw
    MONGODB_PASSWORD: CiQA82pG8JqtxyRKlpxq5xndsSq5UoNxcr1QD6+uzKBq/hyp2jYSOQDs4GkHffiCJguePSh0xNHb4ZNSEwQBB7r0okU2j4P+5LBYay68bz+TV4eA+E6ln5Lk0NqvplhbwA==
